# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michael Hernandez
tagline:          ''
description:      'My Awesome website'
url:              http://zephyrie.github.io
baseurl:          /

author:
  name:           'Michael Hernandez'
  url:            https://twitter.com/zephyrie13

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/zephyrie/zephyrie.github.io

prose:
  siteurl: zephyrie.github.io
  ignore:
    - /_config.yml
    - /atom.xml
    - /LICENSE.md
    - /_layouts
    - /_includes
    - /public
    - /.travis.yml
    - /.gitignore
    - /deploy.sh
    - /deploy_key.enc
    - /Gemfile
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"

