# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ms. Trudeau
tagline:          'Come in, sit down, have a cup of tea and follow along'
description:      'Come in, sit down, have a cup of tea and follow along'
url:              http://zephyrie.github.io
baseurl:          /

author:
  name:           'Jourdan Trudeau'
  url:            https://www.jourdantrudeau.com

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/zephyrie/zephyrie.github.io

prose:
  siteurl: zephyrie.github.io
  media: 'media'
  ignore:
    - /atom.xml
    - /LICENSE.md
    - /.travis.yml
    - /.gitignore
    - /deploy.sh
    - /deploy_key.enc
    - /Gemfile